importScripts('./assets/brand-canon-v28.js');

const BRAND=self.EL_ERRANTE_BRAND_V28;
const CACHE=BRAND.cache;
const GENERATED=[
  './assets/generated/data-v28.js','./assets/generated/app-v28.js','./assets/generated/preprod-v28.js',
  './assets/generated/manifest-v28.json','./assets/data-finalize-v28.js',
  './assets/app-contract-v28.js','./assets/preprod-contract-v28.js'
];
const COMPATIBILITY=[
  './assets/data.js','./assets/app.js','./assets/preprod.js',
  './assets/source/v040-app-001.b64','./assets/source/v040-app-002.b64','./assets/source/v040-app-003.b64',
  './assets/source/v040-app-004.b64','./assets/source/v040-app-005.b64','./assets/source/v040-app-006.b64',
  './assets/source/v040-data-001.b64','./assets/source/v040-data-002.b64','./assets/source/v040-data-003.b64','./assets/source/v040-data-004.b64',
  './assets/source/v040-preprod-001a.b64','./assets/source/v040-preprod-001b.b64','./assets/source/v040-preprod-001c.b64','./assets/source/v040-preprod-001d.b64',
  './assets/source/v040-preprod-002.b64','./assets/source/v040-preprod-003.b64'
];
const CORE=[
  './index.html','./historia.html','./nosotros.html','./equipo.html','./tienda.html','./producto.html','./en-casa.html',
  './en-movimiento.html','./bitacora.html','./articulo.html','./recetas.html','./receta.html','./herramientas.html',
  './cobertura.html','./ayuda.html','./checkout.html','./cuenta.html','./legal.html','./acceso.html','./centro-interno.html',
  './admin.html','./activacion.html','./control.html','./operacion.html','./finanzas.html','./studio.html','./actas.html','./presentacion.html',
  './assets/styles.css','./assets/styles/brand-v1.css','./assets/internal-v30.css','./assets/internal-v31.css','./assets/master-data-v10.css','./assets/master-cost-proposals-v11.css','./assets/operational-evidence-v330.css','./assets/finance-v32.css','./assets/finance-v321.css','./assets/finance-v322.css','./assets/finance-v323.css','./assets/finance-v324.css','./assets/finance-v325.css','./assets/finance-v326.css','./assets/finance-v327.css','./assets/finance-v328.css','./assets/finance-v329.css','./assets/brand-canon-v28.js','./assets/products-v6.js','./assets/runtime.js',
  './assets/content-v5.js','./assets/content-v17.js','./assets/editorial-v29.js','./assets/public-actions-v29.js','./assets/public-commerce-guard-v29.js','./assets/commerce-ux-v18.js','./assets/trust-v19.js',
  './assets/access-v31.js','./assets/internal-shell-v31.js','./assets/internal-demo-v311.js','./assets/master-data-v10.js','./assets/master-cost-proposals-v11.js','./assets/operational-evidence-v330.js','./assets/finance-workbench-v31.js','./assets/finance-starter-v31.js','./assets/finance-depth-v32.js','./assets/finance-ledger-v321.js','./assets/finance-unit-economics-v322.js','./assets/finance-cash-trends-v323.js','./assets/finance-scenarios-v324.js','./assets/finance-decisions-v325.js','./assets/finance-procurement-v326.js','./assets/finance-executive-v327.js','./assets/finance-readiness-v328.js','./assets/finance-demo-v329.js',
  './assets/activation-v20.js','./assets/activation-v23.js','./assets/activation-v24.js','./assets/activation-v25.js',
  './assets/control-v30.js','./assets/mfo-v30.js','./assets/daily-ops-v21.js','./assets/production-v22.js','./assets/materials-data-v23.js','./assets/materials-v23.js',
  './assets/measurement-v24.js','./assets/procurement-v25.js','./assets/procurement-v25-guard.js','./assets/finance-v27.js',
  './assets/host-mode.js','./assets/commerce-runtime-config.js','./assets/commerce-config-v14.js','./assets/checkout-v15.js',
  './assets/admin-v15.js','./assets/commerce-v14.js','./assets/commerce-v14.css','./assets/commerce-v15.css','./assets/commerce-v16.css','./assets/commerce-v18.css','./assets/trust-v19.css','./assets/activation-v20.css',
  './assets/daily-ops-v21.css','./assets/production-v22.css','./assets/materials-v23.css','./assets/measurement-v24.css','./assets/procurement-v25.css','./assets/finance-v27.css','./assets/operations-v16.js','./assets/control.js','./assets/presentation.js',
  ...Object.values(BRAND.assets).filter(path=>path.startsWith('assets/')).map(path=>'./'+path),
  './assets/offer-studio-v09.js','./assets/offer-studio-v09.css','./assets/offer-governance-v09.js','./assets/offer-acts-preflight-v09.js','./assets/offer-acts-v09.js','./assets/offer-acts-v09.css','./assets/aire-tiempo-committee-v09.js','./assets/aire-tiempo-committee-v09.css',
  './backend/supabase/schema-v19.sql','./backend/supabase/schema-v20.sql','./backend/supabase/schema-v21.sql','./backend/supabase/schema-v22.sql','./backend/supabase/schema-v23.sql','./backend/supabase/schema-v24.sql','./backend/supabase/schema-v25.sql',
  './documentacion/modelo-oferta-v09.json','./documentacion/sesiones/aire-y-tiempo-paquete-comite-v09.json','./documentacion/sesiones/AIRE_Y_TIEMPO_PAQUETE_COMITE_V09.md','./offline.html','./deploy-version.txt'
];

async function cacheOptional(cache,paths){await Promise.allSettled(paths.map(async path=>{const response=await fetch(path,{cache:'no-store'});if(response.ok)await cache.put(path,response);}));}
self.addEventListener('install',event=>{event.waitUntil((async()=>{const cache=await caches.open(CACHE);await cache.addAll([...new Set(CORE)]);await cacheOptional(cache,[...GENERATED,...COMPATIBILITY]);})());self.skipWaiting();});
self.addEventListener('activate',event=>{event.waitUntil(caches.keys().then(keys=>Promise.all(keys.filter(key=>key.startsWith('el-errante-')&&key!==CACHE).map(key=>caches.delete(key)))).then(()=>self.clients.claim()));});
function canonicalRequest(request){const url=new URL(request.url);const relative=url.pathname.replace(/^.*\/ELERRANTE\//,'').replace(/^\//,'');const resolved=BRAND.resolve(relative);if(!resolved||resolved===relative)return request;return new Request(new URL(resolved,self.registration.scope).toString(),request);}
async function networkFirst(request){try{const response=await fetch(request,{cache:'no-store'});if(response&&response.ok){const cache=await caches.open(CACHE);await cache.put(request,response.clone());}return response;}catch(error){return (await caches.match(request))||(await caches.match('./offline.html'));}}
async function cacheFirst(request){const canonical=canonicalRequest(request);const cached=await caches.match(canonical)||await caches.match(request);if(cached)return cached;const response=await fetch(canonical);if(response&&response.ok&&new URL(canonical.url).origin===self.location.origin){const cache=await caches.open(CACHE);await cache.put(canonical,response.clone());}return response;}
self.addEventListener('fetch',event=>{const request=event.request;if(request.method!=='GET')return;const url=new URL(request.url);if(url.origin!==self.location.origin)return;const fresh=request.mode==='navigate'||request.destination==='document'||url.pathname.endsWith('/deploy-version.txt')||url.pathname.endsWith('/assets/host-mode.js')||url.pathname.endsWith('/assets/commerce-runtime-config.js')||url.pathname.endsWith('/assets/commerce-config-v14.js')||url.pathname.endsWith('/assets/checkout-v15.js')||url.pathname.endsWith('/assets/brand-canon-v28.js')||url.pathname.endsWith('/assets/editorial-v29.js')||url.pathname.endsWith('/assets/public-actions-v29.js')||url.pathname.endsWith('/assets/public-commerce-guard-v29.js')||url.pathname.endsWith('/assets/access-v31.js')||url.pathname.endsWith('/assets/internal-shell-v31.js')||url.pathname.endsWith('/assets/internal-demo-v311.js')||url.pathname.endsWith('/assets/internal-v31.css')||url.pathname.endsWith('/assets/master-data-v10.js')||url.pathname.endsWith('/assets/master-data-v10.css')||url.pathname.endsWith('/assets/master-cost-proposals-v11.js')||url.pathname.endsWith('/assets/master-cost-proposals-v11.css')||url.pathname.endsWith('/assets/operational-evidence-v330.js')||url.pathname.endsWith('/assets/operational-evidence-v330.css')||url.pathname.endsWith('/assets/finance-workbench-v31.js')||url.pathname.endsWith('/assets/finance-starter-v31.js')||url.pathname.endsWith('/assets/finance-depth-v32.js')||url.pathname.endsWith('/assets/finance-v32.css')||url.pathname.endsWith('/assets/finance-ledger-v321.js')||url.pathname.endsWith('/assets/finance-v321.css')||url.pathname.endsWith('/assets/finance-unit-economics-v322.js')||url.pathname.endsWith('/assets/finance-v322.css')||url.pathname.endsWith('/assets/finance-cash-trends-v323.js')||url.pathname.endsWith('/assets/finance-v323.css')||url.pathname.endsWith('/assets/finance-scenarios-v324.js')||url.pathname.endsWith('/assets/finance-v324.css')||url.pathname.endsWith('/assets/finance-decisions-v325.js')||url.pathname.endsWith('/assets/finance-v325.css')||url.pathname.endsWith('/assets/finance-procurement-v326.js')||url.pathname.endsWith('/assets/finance-v326.css')||url.pathname.endsWith('/assets/finance-executive-v327.js')||url.pathname.endsWith('/assets/finance-v327.css')||url.pathname.endsWith('/assets/finance-readiness-v328.js')||url.pathname.endsWith('/assets/finance-v328.css')||url.pathname.endsWith('/assets/finance-demo-v329.js')||url.pathname.endsWith('/assets/finance-v329.css')||url.pathname.endsWith('/assets/materials-data-v23.js')||url.pathname.endsWith('/assets/materials-v23.js')||url.pathname.endsWith('/assets/control-v30.js')||url.pathname.endsWith('/assets/mfo-v30.js')||url.pathname.endsWith('/assets/generated/manifest-v28.json')||url.pathname.endsWith('/materialized-site-v28.json');event.respondWith(fresh?networkFirst(request):cacheFirst(request));});
self.addEventListener('message',event=>{if(event.data==='SKIP_WAITING')self.skipWaiting();});
