const {test,expect}=require('@playwright/test');

const demoSession=()=>({version:'3.1.0',username:'demo',displayName:'Demo',role:'Administrador',issuedAt:new Date().toISOString(),expiresAt:new Date(Date.now()+8*3600000).toISOString()});
async function session(page){await page.addInitScript(()=>{if(sessionStorage.getItem('ee_v329_test_boot'))return;sessionStorage.setItem('ee_v329_test_boot','1');sessionStorage.setItem('ee_v31_session',JSON.stringify({version:'3.1.0',username:'demo',displayName:'Demo',role:'Administrador',issuedAt:new Date().toISOString(),expiresAt:new Date(Date.now()+8*3600000).toISOString()}));localStorage.removeItem('ee_v30_mfo_snapshot');localStorage.removeItem('ee_v31_finance_working_model');localStorage.removeItem('ee_v31_finance_history');localStorage.removeItem('ee_v329_finance_demo');});}
async function openEmpty(page){await page.goto('/finanzas.html');await expect(page.getByRole('heading',{name:'Carga el baseline privado del MFO.'})).toBeVisible();await expect(page.getByRole('button',{name:'Cargar demo financiera',exact:true})).toBeVisible();}

test.describe('Demo financiera guiada V3.2.9',()=>{
 test('ofrece una demo explícitamente sintética desde el estado vacío',async({page})=>{await session(page);await openEmpty(page);await expect(page.getByText('Demo aislada y reversible.',{exact:true})).toBeVisible();const generated=await page.evaluate(()=>window.EL_ERRANTE_FINANCE_DEMO_V329.makeDemo());expect(generated.meta.demoVersion).toBe('3.2.9');expect(generated.meta.source).toContain('sintéticos');expect(generated.productCosts.some(p=>p.directCost>0)).toBe(true);expect(generated.planSales.some(r=>r.sales>0)).toBe(true);});

 test('carga un escenario demostrable con plan, costo, venta y caja',async({page})=>{await session(page);await openEmpty(page);await page.getByRole('button',{name:'Cargar demo financiera',exact:true}).click();await expect(page.locator('html')).toHaveAttribute('data-finance-demo-version','3.2.9');await expect(page.getByText('Datos sintéticos activos',{exact:true})).toBeVisible();const state=await page.evaluate(()=>({snapshot:JSON.parse(localStorage.getItem('ee_v30_mfo_snapshot')),orders:JSON.parse(localStorage.getItem('ee_v14_orders')),cash:JSON.parse(localStorage.getItem('ee_v323_cash_counts')),summary:window.EL_ERRANTE_FINANCE_V327.summary(window.EL_ERRANTE_FINANCE_V31.working(),new Date().toLocaleDateString('en-CA',{timeZone:'America/Bogota'}).slice(0,7))}));expect(state.snapshot.meta.demoVersion).toBe('3.2.9');expect(state.orders[0].demoV329).toBe(true);expect(state.cash[0].demoV329).toBe(true);expect(state.summary.salesPlan).toBeGreaterThan(0);expect(state.summary.realSales).toBeGreaterThan(0);expect(state.summary.observedCash).toBeGreaterThan(0);});

 test('al salir restaura exactamente los hechos locales previos',async({page})=>{await page.addInitScript(()=>{if(sessionStorage.getItem('ee_v329_restore_boot'))return;sessionStorage.setItem('ee_v329_restore_boot','1');sessionStorage.setItem('ee_v31_session',JSON.stringify({version:'3.1.0',username:'demo',displayName:'Demo',role:'Administrador',issuedAt:new Date().toISOString(),expiresAt:new Date(Date.now()+8*3600000).toISOString()}));localStorage.removeItem('ee_v30_mfo_snapshot');localStorage.removeItem('ee_v31_finance_working_model');localStorage.removeItem('ee_v31_finance_history');localStorage.removeItem('ee_v329_finance_demo');localStorage.setItem('ee_v14_orders',JSON.stringify([{id:'PREEXISTENTE',status:'approved',total:12345,items:[]}]));localStorage.setItem('ee_v27_finance_movements',JSON.stringify([{id:'MOV-PREVIO',date:'2026-08-01',type:'operating_expense',amount:321}]));});await openEmpty(page);const before=await page.evaluate(()=>({orders:localStorage.getItem('ee_v14_orders'),moves:localStorage.getItem('ee_v27_finance_movements')}));await page.getByRole('button',{name:'Cargar demo financiera',exact:true}).click();await expect(page.getByText('Datos sintéticos activos',{exact:true})).toBeVisible();await page.getByRole('button',{name:'Salir y restaurar datos',exact:true}).click();await expect(page.getByRole('button',{name:'Cargar demo financiera',exact:true})).toBeVisible();const after=await page.evaluate(()=>({orders:localStorage.getItem('ee_v14_orders'),moves:localStorage.getItem('ee_v27_finance_movements'),snapshot:localStorage.getItem('ee_v30_mfo_snapshot'),marker:localStorage.getItem('ee_v329_finance_demo')}));expect(after.orders).toBe(before.orders);expect(after.moves).toBe(before.moves);expect(after.snapshot).toBeNull();expect(after.marker).toBeNull();});

 test('no ofrece demo cuando ya existe un baseline financiero',async({page})=>{await page.addInitScript(()=>{sessionStorage.setItem('ee_v31_session',JSON.stringify({version:'3.1.0',username:'demo',displayName:'Demo',role:'Administrador',issuedAt:new Date().toISOString(),expiresAt:new Date(Date.now()+8*3600000).toISOString()}));localStorage.setItem('ee_v30_mfo_snapshot',JSON.stringify({schemaVersion:'3.0',meta:{modelName:'Baseline privado',reconciliation:'PASS'},planSales:[],productCosts:[],cashFlow:[],scenarios:[],assumptions:[],decisions:[],pending:[]}));localStorage.removeItem('ee_v31_finance_working_model');localStorage.removeItem('ee_v329_finance_demo');});await page.goto('/finanzas.html');await expect(page.getByRole('button',{name:'Cargar demo financiera',exact:true})).toHaveCount(0);await expect(page.getByText('Datos sintéticos activos',{exact:true})).toHaveCount(0);});

 test('banner demo no desborda el documento móvil',async({page},testInfo)=>{test.skip(!testInfo.project.name.includes('mobile'),'Validación móvil');await session(page);await openEmpty(page);await page.getByRole('button',{name:'Cargar demo financiera',exact:true}).click();await expect(page.locator('[data-v329-demo-banner]')).toBeVisible();const g=await page.evaluate(()=>{const r=document.querySelector('[data-v329-demo-banner]').getBoundingClientRect();return {overflow:document.documentElement.scrollWidth-document.documentElement.clientWidth,left:r.left,right:r.right,viewport:innerWidth};});expect(g.overflow).toBeLessThanOrEqual(2);expect(g.left).toBeGreaterThanOrEqual(-2);expect(g.right).toBeLessThanOrEqual(g.viewport+2);});
});