const {test,expect}=require('@playwright/test');
const SESSION={version:'3.1.1',username:'juan',displayName:'Juan',role:'Administrador'};
const R1={eventId:'STD-V15-HFS-R1',type:'MATERIALIZED',at:'2026-08-10T05:00:00.000Z',materialId:'MP-HFS',materialName:'Harina Flor Suprema',unit:'g',fromRevision:0,toRevision:1,baselineCost:2.8,fromCost:2.8,toCost:3.4};
const R2={eventId:'STD-V15-HFS-R2',type:'MATERIALIZED',at:'2026-08-10T07:00:00.000Z',materialId:'MP-HFS',materialName:'Harina Flor Suprema',unit:'g',fromRevision:1,toRevision:2,baselineCost:2.8,fromCost:3.4,toCost:4.2};
const PURCHASE={id:'COM-V15-1',materialId:'MP-HFS',supplier:'Molinos V15',receivedDate:'2026-08-10',quantity:1000,totalCost:4000,unitCost:4,createdAt:'2026-08-10T06:00:00.000Z',dataStatus:'OBSERVADO'};
const PURCHASE_SNAPSHOT={eventId:'HIST-PUR-V15-1',type:'PURCHASE_STANDARD_SNAPSHOT',version:'1.4.0',factType:'PURCHASE_RECEIPT',factId:'COM-V15-1',materialId:'MP-HFS',materialName:'Harina Flor Suprema',effectiveAt:'2026-08-10T06:00:00.000Z',capturedAt:'2026-08-10T06:01:00.000Z',observedUnitCost:4,standardUnitCost:3.4,baselineUnitCost:2.8,standardRevision:1,standardSource:'MATERIALIZATION_LEDGER_V12',costOrigin:'MATERIALIZED_STANDARD',complete:true};
function activeOrder(){return {id:'ORDER-V15-1',status:'approved',createdAt:'2026-08-10T05:30:00.000Z',updatedAt:'2026-08-10T05:30:00.000Z',delivery:{requestedDate:'2026-08-10'},items:[{productId:'margherita-del-taller',name:'Margherita del Taller',quantity:1,unitPrice:20900}]};}
async function seed(page,{stock={'MP-HFS':1000},purchases=[PURCHASE],purchaseOrders=[],orders=[],events=[R1,R2],snapshots=[PURCHASE_SNAPSHOT]}={}){await page.addInitScript(({session,stock,purchases,purchaseOrders,orders,events,snapshots})=>{sessionStorage.setItem('ee_v31_session',JSON.stringify({...session,issuedAt:new Date().toISOString(),expiresAt:new Date(Date.now()+8*3600000).toISOString()}));localStorage.setItem('ee_v23_material_stock',JSON.stringify(stock));localStorage.setItem('ee_v24_material_purchases',JSON.stringify(purchases));localStorage.setItem('ee_v25_purchase_orders',JSON.stringify(purchaseOrders));localStorage.setItem('ee_v14_orders',JSON.stringify(orders));localStorage.setItem('ee_v12_cost_materialization_events',JSON.stringify(events));localStorage.setItem('ee_v14_cost_snapshot_events',JSON.stringify(snapshots));localStorage.setItem('ee_v14_cost_snapshot_state',JSON.stringify({version:'1.4.0',initializedAt:'2026-08-10T04:00:00.000Z',knownPurchaseIds:purchases.map(x=>String(x.id)),knownMovementIds:[],knownOrderStatuses:Object.fromEntries(orders.map(x=>[String(x.id),String(x.status||'')]))}));},{session:SESSION,stock,purchases,purchaseOrders,orders,events,snapshots});}
async function openFinance(page){await page.goto('/finanzas.html');await expect(page.locator('body')).toHaveAttribute('data-v31-authenticated','true');await page.waitForFunction(()=>Boolean(window.EL_ERRANTE_HISTORICAL_COST_V14&&window.EL_ERRANTE_INVENTORY_VALUATION_V15&&window.EL_ERRANTE_FINANCE_INVENTORY_VALUATION_V15));await expect(page.locator('#finance-inventory-valuation-v15')).toBeVisible();}
test.describe('Datos maestros V1.5 · inventario valorizado y variaciones',()=>{
 test('valor estándar y referencia observada permanecen separados',async({page})=>{await seed(page);await openFinance(page);const row=await page.evaluate(()=>window.EL_ERRANTE_INVENTORY_VALUATION_V15.materialRows().find(x=>x.id==='MP-HFS'));expect(row.stockQty).toBe(1000);expect(row.standardUnitCost).toBeCloseTo(4.2,6);expect(row.standardValue).toBeCloseTo(4200,6);expect(row.observedReferenceUnitCost).toBeCloseTo(4,6);expect(row.observedReferenceValue).toBeCloseTo(4000,6);expect(row.standardValue).not.toBe(row.observedReferenceValue);});
 test('variación de compra usa estándar histórico de V1.4 y no el estándar vigente posterior',async({page})=>{await seed(page);await openFinance(page);const result=await page.evaluate(()=>{const api=window.EL_ERRANTE_INVENTORY_VALUATION_V15;return {variance:api.purchaseVariances()[0],current:api.currentStandard('MP-HFS')};});expect(result.variance.standardUnitCost).toBeCloseTo(3.4,6);expect(result.variance.observedUnitCost).toBeCloseTo(4,6);expect(result.variance.variancePct).toBeCloseTo((4-3.4)/3.4,6);expect(result.variance.alert).toBe(true);expect(result.current.unitCost).toBeCloseTo(4.2,6);});
 test('inventario sin conteo permanece desconocido y no se convierte en cero',async({page})=>{await seed(page,{stock:{},orders:[activeOrder()]});await openFinance(page);const row=await page.evaluate(()=>window.EL_ERRANTE_INVENTORY_VALUATION_V15.materialRows().find(x=>x.id==='MP-HFS'));expect(row.requirementQty).toBeGreaterThan(0);expect(row.stockKnown).toBe(false);expect(row.stockQty).toBeNull();expect(row.standardValue).toBeNull();expect(row.coverageStatus).toBe('unknown');});
 test('compromiso emitido y recepción observada no se confunden',async({page})=>{const po={id:'OC-V15-1',materialId:'MP-HFS',supplier:'Molinos V15',status:'partial',requestedQty:10,receivedQty:4,unitCost:4};await seed(page,{purchaseOrders:[po]});await openFinance(page);const result=await page.evaluate(()=>{const api=window.EL_ERRANTE_INVENTORY_VALUATION_V15;const row=api.materialRows().find(x=>x.id==='MP-HFS');return {supply:api.supplyByMaterial(),row,purchase:api.purchaseEvidence()[0]};});expect(result.row.issuedQty).toBe(6);expect(result.supply.committedCash).toBe(24);expect(result.purchase.quantity).toBe(1000);expect(result.purchase.observedUnitCost).toBe(4);});
 test('leer V1.5 no muta stock, compras, órdenes, pedidos ni ledger histórico',async({page})=>{const po={id:'OC-V15-2',materialId:'MP-HFS',status:'ordered',requestedQty:20,receivedQty:0,unitCost:4};await seed(page,{purchaseOrders:[po],orders:[activeOrder()]});await openFinance(page);const result=await page.evaluate(()=>{const keys=['ee_v23_material_stock','ee_v24_material_purchases','ee_v25_purchase_orders','ee_v14_orders','ee_v12_cost_materialization_events','ee_v14_cost_snapshot_events'];const before=Object.fromEntries(keys.map(k=>[k,localStorage.getItem(k)]));const api=window.EL_ERRANTE_INVENTORY_VALUATION_V15;api.snapshot();api.summary();api.materialRows();api.purchaseVariances();api.alerts();const after=Object.fromEntries(keys.map(k=>[k,localStorage.getItem(k)]));return {before,after};});expect(result.after).toEqual(result.before);});
 test('Finanzas explica que la referencia observada no es valorización contable por lotes',async({page})=>{await seed(page);await openFinance(page);await expect(page.locator('#finance-inventory-valuation-v15')).toContainText('Referencia observada');await expect(page.locator('#finance-inventory-valuation-v15')).toContainText('no FIFO');await expect(page.locator('#finance-inventory-valuation-v15')).toContainText('estándar histórico');await expect(page.locator('#finance-inventory-valuation-v15')).toContainText('Exposición de caja');});
 test('no genera desbordamiento horizontal en Finanzas móvil con V1.5',async({page},testInfo)=>{test.skip(!testInfo.project.name.includes('mobile'),'Validación exclusiva del proyecto móvil');await seed(page);await openFinance(page);const overflow=await page.evaluate(()=>document.documentElement.scrollWidth-document.documentElement.clientWidth);expect(overflow).toBeLessThanOrEqual(2);});
});