const {test,expect}=require('@playwright/test');
const SESSION={version:'3.1.1',username:'juan',displayName:'Juan',role:'Administrador'};
const MEASUREMENT={id:'MED-V16-1',kind:'product',referenceId:'EE-MAR-01',referenceName:'Margherita del Taller',batchCode:'MAR-2026-08-09-01',productionDate:'2026-08-09',expectedQty:1,actualQty:0.93,wasteQty:0.07,unit:'unidad',note:'Lote control V1.6',createdAt:'2026-08-09T18:00:00.000Z',dataStatus:'MEDIDO'};
const R1={eventId:'STD-V16-HFS-R1',type:'MATERIALIZED',at:'2026-08-09T05:00:00.000Z',materialId:'MP-HFS',materialName:'Harina Flor Suprema',unit:'g',fromRevision:0,toRevision:1,baselineCost:2.8,fromCost:2.8,toCost:3.4};
const R2={eventId:'STD-V16-HFS-R2',type:'MATERIALIZED',at:'2026-08-10T07:00:00.000Z',materialId:'MP-HFS',materialName:'Harina Flor Suprema',unit:'g',fromRevision:1,toRevision:2,baselineCost:2.8,fromCost:3.4,toCost:4.2};
async function seed(page,{measurements=[MEASUREMENT],consumption=[],purchases=[],events=[R1,R2]}={}){await page.addInitScript(({session,measurements,consumption,purchases,events})=>{sessionStorage.setItem('ee_v31_session',JSON.stringify({...session,issuedAt:new Date().toISOString(),expiresAt:new Date(Date.now()+8*3600000).toISOString()}));localStorage.setItem('ee_v24_production_measurements',JSON.stringify(measurements));localStorage.setItem('ee_v16_batch_consumption_events',JSON.stringify(consumption));localStorage.setItem('ee_v24_material_purchases',JSON.stringify(purchases));localStorage.setItem('ee_v12_cost_materialization_events',JSON.stringify(events));localStorage.setItem('ee_v14_cost_snapshot_events','[]');localStorage.setItem('ee_v14_cost_snapshot_state',JSON.stringify({version:'1.4.0',initializedAt:'2026-08-09T04:00:00.000Z',knownPurchaseIds:[],knownMovementIds:[],knownOrderStatuses:{}}));},{session:SESSION,measurements,consumption,purchases,events});}
async function openOperation(page){await page.goto('/operacion.html');await expect(page.locator('body')).toHaveAttribute('data-v31-authenticated','true');await page.waitForFunction(()=>Boolean(window.EL_ERRANTE_HISTORICAL_COST_V14&&window.EL_ERRANTE_PRODUCTION_COST_V16&&window.EL_ERRANTE_OPERATION_PRODUCTION_COST_V16));await expect(page.locator('#production-cost-v16')).toBeVisible();}
async function openFinance(page){await page.goto('/finanzas.html');await expect(page.locator('body')).toHaveAttribute('data-v31-authenticated','true');await page.waitForFunction(()=>Boolean(window.EL_ERRANTE_HISTORICAL_COST_V14&&window.EL_ERRANTE_PRODUCTION_COST_V16&&window.EL_ERRANTE_FINANCE_PRODUCTION_COST_V16));await expect(page.locator('#finance-production-cost-v16')).toBeVisible();}
async function completeBatch(page,{withActualCosts=true,multiplier=1}={}){await page.evaluate(({withActualCosts,multiplier})=>{const api=window.EL_ERRANTE_PRODUCTION_COST_V16;const batch=api.batchRows()[0];const rows=batch.lines.map((line,index)=>({id:`CONS-COMPLETE-${index}`,type:'BATCH_CONSUMPTION_RECORDED',version:'1.6.0',batchId:batch.batchId,batchCode:batch.batchCode,productionDate:batch.productionDate,referenceId:batch.referenceId,referenceName:batch.referenceName,materialId:line.materialId,materialName:line.material?.name||line.materialId,unit:line.material?.unit||'',observedQty:line.expectedQty*multiplier,observedUnitCost:withActualCosts?(line.standardUnitCost===null?null:line.standardUnitCost+0.2):null,supportRef:withActualCosts?'SOP-V16':'',note:'Prueba V1.6',supersedes:null,createdAt:new Date(Date.now()+index).toISOString(),createdBy:'Test',dataStatus:'OBSERVADO'}));localStorage.setItem('ee_v16_batch_consumption_events',JSON.stringify(rows));api.notify('test-complete');},{withActualCosts,multiplier});}
test.describe('Datos maestros V1.6 · costo real de producción y merma',()=>{
 test('estándar del lote se reconstruye as-of y no usa una revisión posterior',async({page})=>{await seed(page);await openFinance(page);const line=await page.evaluate(()=>window.EL_ERRANTE_PRODUCTION_COST_V16.batchRows()[0].lines.find(x=>x.materialId==='MP-HFS'));expect(line.standardUnitCost).toBeCloseTo(3.4,6);expect(line.standardRevision).toBe(1);});
 test('consumo faltante permanece desconocido y nunca se interpreta como cero',async({page})=>{await seed(page);await openFinance(page);const batch=await page.evaluate(()=>window.EL_ERRANTE_PRODUCTION_COST_V16.batchRows()[0]);expect(batch.consumptionComplete).toBe(false);expect(batch.observedLines).toBe(0);expect(batch.observedAtStandardCost).toBeNull();expect(batch.actualObservedCost).toBeNull();expect(batch.lines.every(line=>line.observedQty===null)).toBe(true);});
 test('una última compra no se atribuye automáticamente como costo real del lote',async({page})=>{await seed(page,{purchases:[{id:'COM-V16-1',materialId:'MP-HFS',supplier:'Molino',receivedDate:'2026-08-09',quantity:1000,totalCost:3900,unitCost:3.9}]});await openFinance(page);await completeBatch(page,{withActualCosts:false});const batch=await page.evaluate(()=>window.EL_ERRANTE_PRODUCTION_COST_V16.batchRows()[0]);expect(batch.consumptionComplete).toBe(true);expect(batch.actualCostComplete).toBe(false);expect(batch.actualObservedCost).toBeNull();expect(batch.observedAtStandardCost).not.toBeNull();});
 test('consumo completo separa eficiencia a estándar de costo real observado',async({page})=>{await seed(page);await openFinance(page);await completeBatch(page,{withActualCosts:true,multiplier:1.1});const batch=await page.evaluate(()=>window.EL_ERRANTE_PRODUCTION_COST_V16.batchRows()[0]);expect(batch.consumptionComplete).toBe(true);expect(batch.actualCostComplete).toBe(true);expect(batch.observedAtStandardCost).toBeGreaterThan(batch.expectedStandardCost);expect(batch.usageVariancePct).toBeCloseTo(0.1,5);expect(batch.actualObservedCost).toBeGreaterThan(batch.observedAtStandardCost);});
 test('captura y corrección son append-only por lote y material',async({page})=>{await seed(page);await openOperation(page);const result=await page.evaluate(()=>{const writer=window.EL_ERRANTE_OPERATION_PRODUCTION_COST_V16;const first=writer.saveConsumption({batchId:'MED-V16-1',materialId:'MP-HFS',observedQty:'180',observedUnitCost:'3.6',supportRef:'FAC-1',note:'Primera lectura'});const second=writer.saveConsumption({batchId:'MED-V16-1',materialId:'MP-HFS',observedQty:'182',observedUnitCost:'3.6',supportRef:'FAC-1',note:'Corrección',supersedes:first.id});const api=window.EL_ERRANTE_PRODUCTION_COST_V16;return {rows:JSON.parse(localStorage.getItem('ee_v16_batch_consumption_events')),active:api.activeConsumptions(),first,second};});expect(result.rows).toHaveLength(2);expect(result.second.supersedes).toBe(result.first.id);expect(result.active).toHaveLength(1);expect(result.active[0].observedQty).toBe(182);});
 test('un costo observado exige referencia de soporte',async({page})=>{await seed(page);await openOperation(page);const message=await page.evaluate(()=>{try{window.EL_ERRANTE_OPERATION_PRODUCTION_COST_V16.saveConsumption({batchId:'MED-V16-1',materialId:'MP-HFS',observedQty:'180',observedUnitCost:'3.6',supportRef:''});return '';}catch(error){return error.message;}});expect(message).toContain('referencia');expect(await page.evaluate(()=>JSON.parse(localStorage.getItem('ee_v16_batch_consumption_events')).length)).toBe(0);});
 test('leer V1.6 desde Finanzas no muta mediciones, consumos ni estándares',async({page})=>{await seed(page);await openFinance(page);const result=await page.evaluate(()=>{const keys=['ee_v24_production_measurements','ee_v16_batch_consumption_events','ee_v12_cost_materialization_events','ee_v14_cost_snapshot_events'];const before=Object.fromEntries(keys.map(k=>[k,localStorage.getItem(k)]));const api=window.EL_ERRANTE_PRODUCTION_COST_V16;api.snapshot();api.summary();api.batchRows();api.alerts();const after=Object.fromEntries(keys.map(k=>[k,localStorage.getItem(k)]));return {before,after};});expect(result.after).toEqual(result.before);});
 test('Finanzas explica límites de costo real y cobertura',async({page})=>{await seed(page);await openFinance(page);await expect(page.locator('#finance-production-cost-v16')).toContainText('última compra no se atribuye automáticamente');await expect(page.locator('#finance-production-cost-v16')).toContainText('costo real observado');await expect(page.locator('#finance-production-cost-v16')).toContainText('costo conocido');});
 test('no genera desbordamiento horizontal en móvil',async({page},testInfo)=>{test.skip(!testInfo.project.name.includes('mobile'),'Validación exclusiva del proyecto móvil');await seed(page);await openOperation(page);let overflow=await page.evaluate(()=>document.documentElement.scrollWidth-document.documentElement.clientWidth);expect(overflow).toBeLessThanOrEqual(2);await page.goto('/finanzas.html');await page.waitForFunction(()=>Boolean(window.EL_ERRANTE_FINANCE_PRODUCTION_COST_V16));overflow=await page.evaluate(()=>document.documentElement.scrollWidth-document.documentElement.clientWidth);expect(overflow).toBeLessThanOrEqual(2);});
});