begin;

create table if not exists public.material_master (
  id text primary key,
  name text not null,
  unit text not null,
  provisional_unit_cost numeric(14,4),
  data_status text not null default 'PENDIENTE',
  confidence text,
  source_note text,
  active boolean not null default true,
  updated_at timestamptz not null default now(),
  updated_by uuid references auth.users(id)
);

create table if not exists public.product_bom (
  id bigint generated by default as identity primary key,
  product_sku text not null,
  material_id text not null references public.material_master(id),
  quantity numeric(14,4) not null check (quantity >= 0),
  data_status text not null default 'PENDIENTE',
  valid_from date not null default current_date,
  valid_to date,
  source_note text,
  updated_at timestamptz not null default now(),
  updated_by uuid references auth.users(id),
  unique(product_sku, material_id, valid_from)
);

create table if not exists public.material_inventory (
  material_id text primary key references public.material_master(id),
  quantity numeric(14,4) not null default 0 check (quantity >= 0),
  counted_at timestamptz not null default now(),
  note text,
  updated_by uuid references auth.users(id)
);

alter table public.material_master enable row level security;
alter table public.product_bom enable row level security;
alter table public.material_inventory enable row level security;

drop policy if exists "admins read material master" on public.material_master;
create policy "admins read material master" on public.material_master for select to authenticated using (public.is_admin());
drop policy if exists "admins manage material master" on public.material_master;
create policy "admins manage material master" on public.material_master for all to authenticated using (public.is_admin()) with check (public.is_admin());

drop policy if exists "admins read product bom" on public.product_bom;
create policy "admins read product bom" on public.product_bom for select to authenticated using (public.is_admin());
drop policy if exists "admins manage product bom" on public.product_bom;
create policy "admins manage product bom" on public.product_bom for all to authenticated using (public.is_admin()) with check (public.is_admin());

drop policy if exists "admins read material inventory" on public.material_inventory;
create policy "admins read material inventory" on public.material_inventory for select to authenticated using (public.is_admin());
drop policy if exists "admins manage material inventory" on public.material_inventory;
create policy "admins manage material inventory" on public.material_inventory for all to authenticated using (public.is_admin()) with check (public.is_admin());

create or replace function public.save_material_inventory_v23(p_rows jsonb)
returns integer
language plpgsql
security definer
set search_path = public
as $$
declare
  v_row jsonb;
  v_count integer := 0;
begin
  if not public.is_admin() then
    raise exception 'Acceso administrativo requerido';
  end if;
  if jsonb_typeof(p_rows) <> 'array' then
    raise exception 'Se esperaba un arreglo de inventarios';
  end if;
  for v_row in select value from jsonb_array_elements(p_rows)
  loop
    if coalesce(v_row->>'material_id','') = '' then
      raise exception 'material_id es obligatorio';
    end if;
    insert into public.material_inventory(material_id, quantity, counted_at, note, updated_by)
    values (
      v_row->>'material_id',
      greatest(0, coalesce((v_row->>'quantity')::numeric,0)),
      now(),
      nullif(v_row->>'note',''),
      auth.uid()
    )
    on conflict(material_id) do update set
      quantity=excluded.quantity,
      counted_at=excluded.counted_at,
      note=excluded.note,
      updated_by=excluded.updated_by;
    v_count := v_count + 1;
  end loop;
  insert into public.admin_audit_log(actor_id, action, entity_type, entity_id, detail)
  values (auth.uid(),'material_inventory_count','material_inventory','batch',jsonb_build_object('rows',v_count));
  return v_count;
end;
$$;

revoke all on function public.save_material_inventory_v23(jsonb) from public, anon;
grant execute on function public.save_material_inventory_v23(jsonb) to authenticated;

insert into public.schema_migrations(version, description)
values ('2.3','Materias primas, BOM provisional e inventario inteligente')
on conflict(version) do nothing;

commit;
